[package]
name = "candle-study"
version = "0.1.0"
edition = "2024"


[dependencies]
#提供张量和基本操作
[target.'cfg(not(target_os = "macos"))'.dependencies]
candle-core = { version = "0.9.1", features = ["cuda"] }
candle-nn = { version = "0.9.1", features = ["cuda"] }

[target.'cfg(target_os = "macos")'.dependencies]
candle-core = { version = "0.9.1" }
candle-nn = { version = "0.9.1" }

#用于数据加载时的随机打乱
rand = "0.9.2"